// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Web_API.Models;

namespace Web_API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20171115221036_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_API.Models.TokenAuth.AccessToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("expires_at");

                    b.Property<string>("token")
                        .HasMaxLength(88);

                    b.Property<int>("user_id");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("auth_access_tokens");
                });

            modelBuilder.Entity("Web_API.Models.TokenAuth.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("access_token_id");

                    b.Property<DateTime>("expires_at")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("id");

                    b.HasIndex("access_token_id")
                        .IsUnique();

                    b.ToTable("auth_refresh_tokens");
                });

            modelBuilder.Entity("Web_API.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("email")
                        .HasMaxLength(60);

                    b.Property<string>("name")
                        .HasMaxLength(60);

                    b.Property<string>("password")
                        .HasMaxLength(88);

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Web_API.Models.TokenAuth.AccessToken", b =>
                {
                    b.HasOne("Web_API.Models.User", "user")
                        .WithMany("Tokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web_API.Models.TokenAuth.RefreshToken", b =>
                {
                    b.HasOne("Web_API.Models.TokenAuth.AccessToken", "access_token")
                        .WithOne("refresh_token")
                        .HasForeignKey("Web_API.Models.TokenAuth.RefreshToken", "access_token_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
