using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace Web_API.Models
{
    public class Post
    {
        //Primary Key
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PostId { get; set; }

        [MaxLength(250)]
        public string Title { get; set; }

        [MaxLength(500)]
        public string Content { get; set; }

        //The Identity option specifies that the value will only be generated by the database when a value is first added to the database.
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime created_at { get; set; }

        // The Computed option specifies that the property's value will be generated by the database when the value is first saved, and subsequently regenerated every time the value is updated.
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime updated_at { get; set; }

        //Foreign Key
        [ForeignKey("Blog")]
        public int BlogId { get; set; }

        protected Blog Blog { get; set; }
    }
}
